language: java
install: mvn install -DskipTests -Dgpg.skip
jdk:
  - oraclejdk8
env:
  - FIREFOX_VERSION=49.0.1 GECKODRIVER_VERSION=v0.11.1 DISPLAY=:99.0 GEOMETRY=1280x1024x16
before_script:
  - "export DISPLAY=:99.0"
script:
  - |
      sudo apt-get -y purge firefox
      sude apt-get -qqy --no-install-recommends install firefox
      sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/*
      curl -L -k --no-verbose -o /tmp/firefox.tar.bz2 "https://download-installer.cdn.mozilla.net/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2"
      sudo apt-get -y purge firefox
      sudo rm -rf /opt/firefox
      sudo tar -C /opt -xjf /tmp/firefox.tar.bz2
      sudo rm /tmp/firefox.tar.bz2
      sudo mv /opt/firefox /opt/firefox-$FIREFOX_VERSION
      sudo ln -fs /opt/firefox-$FIREFOX_VERSION/firefox /usr/bin/firefox
      sudo curl -L -k --no-verbose -o /opt/geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
      sudo tar -xvzf /opt/geckodriver.tar.gz -C /opt
  - mvn clean test -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
  - |
      xvfb-run -e /dev/stdout --server-args="-nolisten tcp $DISPLAY -screen 0 $GEOMETRY -ac +extension RANDR" \
        mvn verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false -Dwebdriver.gecko.driver=/opt/geckodriver -Dgalen.default.browser=firefox
after_failure:
  - find . -name "TestSuite.txt" | xargs cat
