language: java
install: mvn install -DskipTests -Dgpg.skip
jdk:
  - oraclejdk8
env:
  - DISPLAY=:99
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - |
      sudo apt-get -y purge chromium-browser
      export CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
      curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
      unzip chrome-linux.zip
      sudo ln -sf $PWD/chrome-linux/chrome-wrapper /usr/local/bin/chrome
      curl -L -o chromedriver.zip http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
      unzip chromedriver.zip
      export CHROMEDRIVER_PATH=$PWD/chromedriver
  - mvn clean test -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
  - mvn verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false -Dwebdriver.chrome.driver=$CHROMEDRIVER_PATH -Dgalen.default.browser=chrome -Dgalen.browser.viewport.adjustSize=true
before_install:
  - export CHROME_BIN=chromium-browser
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 +extension RANDR -ac -screen 0 1280x1024x16"
after_failure:
  - find . -name "TestSuite.txt" | xargs cat
